import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// One sidebar, generated from the docs/ folder. Order comes from
// sidebar_position in each page's frontmatter.
const sidebars: SidebarsConfig = {
  docs: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
